[package]
name = "play-wgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
wgpu = "0.17"
winit = "0.28"
pollster = "0.3"
