[package]
name = "wgpu-hikari"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
env_logger = "0.10"
log = "0.4"
wgpu = { path = "/home/jimb/rust/wgpu/wgpu" }
winit = "0.28"
pollster = "0.3"
